import "@radix-ui/themes/styles.css"
import "./globals.css"

import { cn } from "@/lib/utils"
import { Theme } from "@radix-ui/themes"
import type { Metadata } from "next"
import { Noto_Sans_JP } from "next/font/google"

const notoSansJp = Noto_Sans_JP({
  weight: ["500", "700"],
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
  preload: false,
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type Props = {
  children: React.ReactNode
}

const RootLayout = (props: Props) => {
  return (
    <html lang={"ja"} suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen font-sans antialiased",
          notoSansJp.variable,
        )}
      >
        <Theme>{props.children}</Theme>
      </body>
    </html>
  )
}

export default RootLayout
